---
# defaults file for playbooks/roles/ocp-cro-operator
cro_enabled: false
cro_install_operator: true
cro_catalogsource_image: ""
cro_catalogsource: "redhat-operators"
cro_upgrade_channel: "stable"
cro_directory: "/tmp/cro"
cro_golang_tarball: "https://go.dev/dl/go1.20.linux-ppc64le.tar.gz"
cro_e2e: false
cro_git_repo: "https://github.com/openshift/cluster-resource-override-admission-operator.git"
cro_podman_password: ""
cro_podman_username: ""
cro_cleanup: true